# Generated by Django 5.1.2 on 2024-10-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thema", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/")),
                ("body", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education", models.CharField(max_length=50)),
                ("specialist", models.CharField(max_length=200)),
                ("discription", models.TextField()),
                ("time", models.CharField(max_length=11)),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expericence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=200)),
                ("time", models.CharField(max_length=11)),
                ("discription", models.TextField()),
                ("salary", models.IntegerField(blank=True, null=True)),
                ("create", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("degre", models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("c_name", models.CharField(max_length=100)),
                ("client_say", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="media/account.png",
                        null=True,
                        upload_to="clients/",
                    ),
                ),
                ("confirm", models.BooleanField(default=False)),
                ("create", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
